// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "oauth-server/app/model"
)

// UserHelper is an autogenerated mock type for the UserHelper type
type UserHelper struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, data
func (_m *UserHelper) CreateUser(ctx context.Context, data *model.RegisterRequest) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RegisterRequest) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserHelper creates a new instance of UserHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserHelper {
	mock := &UserHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
