version: "3.8"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: authentication
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "9000:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - "6380:6379"
