mysql:
  host: 127.0.0.1
  port: 30543
  user: postgres
  password: 123456
  database: authentication

postgres:
  host: 127.0.0.1
  port: 30543
  user: postgres
  password: 123456
  database: authentication

server:
  port: 3000
